<?php

/**
 * @file
 * Administrative interface for the tripal srna 
 */

/**
 * construct form for admin
 */
function tripal_srna_admin_form($form, $form_state) {
}

/**
 * Validate the Admin/Settings form.
 */
function tripal_srna_admin_form_validate($form, &$form_state) {
}

/**
 * Submit the Admin/settings form.
 *
 * the variable_set function will set a presistent variable for whole site
 */
function tripal_srna_admin_form_submit($form, $form_state) {
}
